Make it go

diff --git a/install-docker b/install-docker
--- a/install-docker
+++ b/install-docker
@@ -1,10 +1,15 @@
 #!/bin/bash
 # Docker Community Edition for Linux Mint 19 / Ubuntu 18.04
 
+if [[ $EUID -ne 0 ]]; then
+  echo "ERROR: This script must be run as root" 2>&1
+  exit 1
+fi
+
 apt-get update
-apt-get install apt-transport-https ca-certificates curl software-properties-common
+apt-get -y install apt-transport-https ca-certificates curl software-properties-common
 curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
-apt-key fingerprint 0EBFCD88
+apt-key -y fingerprint 0EBFCD88
 add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
 apt-get update
-apt-get install docker-ce
+apt-get -y install docker-ce
